In [32]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt

In [33]:
def multi_gradient_descent(X,y,m,b,lr,num_iterations):
    total_d_m1 = 0
    total_d_m2 = 0
    total_d_m3 = 0
    total_d_m4 = 0
    total_d_m5 = 0
    total_d_m6 = 0
    total_d_m7 = 0
    total_d_m8 = 0
    total_d_b = 0
    for _ in range(num_iterations):
        for i in range(len(X)):
            x = X[i]
            y_pred = np.dot(m,x) + b
            d_m1 = -2 * x[0] * (y[i] - y_pred)
            d_m2 = -2 * x[1] * (y[i] - y_pred)
            d_m3 = -2 * x[2] * (y[i] - y_pred)
            d_m4 = -2 * x[3] * (y[i] - y_pred)
            d_m5 = -2 * x[4] * (y[i] - y_pred)
            d_m6 = -2 * x[5] * (y[i] - y_pred)
            d_m7 = -2 * x[6] * (y[i] - y_pred)
            d_m8 = -2 * x[7] * (y[i] - y_pred)
            d_b = -2 * (y[i] - y_pred)
            total_d_m1 += d_m1
            total_d_m2 += d_m2
            total_d_m3 += d_m3
            total_d_m4 += d_m4
            total_d_m5 += d_m5
            total_d_m6 += d_m6
            total_d_m7 += d_m7
            total_d_m8 += d_m8
            total_d_b += d_b
        m[0] -= lr * (total_d_m1)/len(X)
        m[1] -= lr * (total_d_m2)/len(X)
        m[2] -= lr * (total_d_m3)/len(X)
        m[3] -= lr * (total_d_m4)/len(X)
        m[4] -= lr * (total_d_m5)/len(X)
        m[5] -= lr * (total_d_m6)/len(X)
        m[6] -= lr * (total_d_m7)/len(X)
        m[7] -= lr * (total_d_m8)/len(X)
        b = lr * (d_b)/len(X)
    return m[0], m[1], m[2], m[3], m[4], m[5], m[6], m[7],b

def normalize(X):
    X_normalized = (X - X.min()) / (X.max() - X.min())
    return X_normalized

In [235]:
concrete_data = pd.read_excel("data/Concrete_Data.xls")
concrete_data.reset_index(drop=True, inplace=True)
concrete_data = concrete_data.rename(columns={'Cement (component 1)(kg in a m^3 mixture)': 'Cement', 
                            'Blast Furnace Slag (component 2)(kg in a m^3 mixture)': 'Blast Furnace Slag',
                            'Fly Ash (component 3)(kg in a m^3 mixture)':'Fly Ash',
                            'Water  (component 4)(kg in a m^3 mixture)':'Water',
                            'Superplasticizer (component 5)(kg in a m^3 mixture)':'Superplasticizer',
                            'Coarse Aggregate  (component 6)(kg in a m^3 mixture)':'Coarse Aggregate',
                            'Fine Aggregate (component 7)(kg in a m^3 mixture)':'Fine Aggregate', 
                            'Age (day)':'Age',
                            'Concrete compressive strength(MPa, megapascals) ':'Strength'}, inplace=False)
concrete_data

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.052780
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.296075
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.284354
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.178794
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.696601
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.768036
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.401235

In [262]:
X = concrete_data.drop(columns=['Strength'])
y = concrete_data["Strength"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train=normalize(np.array(X_train))
y_train=np.array(y_train)

In [263]:
results_normalize = {
    "new m":[],
    "new b": [],
    "MSE": [],
    "R-squared": []
}

m1,m2,m3,m4,m5,m6,m7,m8, b_new= multi_gradient_descent(X_train,y_train, m=[22]*8, b=0, lr=0.1, num_iterations=100)
m_new=[m1,m2,m3,m4,m5,m6,m7,m8]
y_pred = np.dot(X_train,m_new) + b_new
r_2 = round(r2_score(y_train,y_pred),3)
mse = round(mean_squared_error(y_train, y_pred),3)
results_normalize["new m"].append(m_new)
results_normalize["new b"].append(b_new)
results_normalize["MSE"].append(mse)
results_normalize["R-squared"].append(r_2)

In [264]:
results_normalize

{'new m': [[155.6248022834771,
   159.2968275345075,
   103.88738766959467,
   -66.18237471320474,
   48.4089651594456,
   -30.355309456107552,
   26.508124711662305,
   150.41490252969967]],
 'new b': [0.001454907002507045],
 'MSE': [174.159],
 'R-squared': [0.387]}

In [240]:
concrete_data = pd.read_excel("data/Concrete_Data.xls")
concrete_data.reset_index(drop=True, inplace=True)
concrete_data = concrete_data.rename(columns={'Cement (component 1)(kg in a m^3 mixture)': 'Cement', 
                            'Blast Furnace Slag (component 2)(kg in a m^3 mixture)': 'Blast Furnace Slag',
                            'Fly Ash (component 3)(kg in a m^3 mixture)':'Fly Ash',
                            'Water  (component 4)(kg in a m^3 mixture)':'Water',
                            'Superplasticizer (component 5)(kg in a m^3 mixture)':'Superplasticizer',
                            'Coarse Aggregate  (component 6)(kg in a m^3 mixture)':'Coarse Aggregate',
                            'Fine Aggregate (component 7)(kg in a m^3 mixture)':'Fine Aggregate', 
                            'Age (day)':'Age',
                            'Concrete compressive strength(MPa, megapascals) ':'Strength'}, inplace=False)
concrete_data

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.052780
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.296075
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.284354
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.178794
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.696601
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.768036
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.401235

In [241]:
X = concrete_data.drop(columns=['Strength'])
y = concrete_data["Strength"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train=np.array(X_train)
y_train=np.array(y_train)

In [260]:
results_raw = {
    "new m":[],
    "new b": [],
    "MSE": [],
    "R-squared": []
}

m1,m2,m3,m4,m5,m6,m7,m8, b_new= multi_gradient_descent(X_train,y_train, m=[0]*8, b=50, lr=0.0000001, num_iterations=1000)
m_new=[m1,m2,m3,m4,m5,m6,m7,m8]
y_pred = np.dot(X_train,m_new) + b_new
r_2 = round(r2_score(y_train,y_pred),3)
mse = round(mean_squared_error(y_train, y_pred),3)
results_raw["new m"].append(m_new)
results_raw["new b"].append(b_new)
results_raw["MSE"].append(mse)
results_raw["R-squared"].append(r_2)

In [261]:
results_raw

{'new m': [[0.1631367420195216,
   0.15878745587485668,
   0.17573985390019667,
   -0.1546503912367975,
   0.3035765572039831,
   0.01407782147969748,
   -0.025977448222680048,
   0.1705695895103094]],
 'new b': [-3.930215132214092e-09],
 'MSE': [219.445],
 'R-squared': [0.228]}